server:
  port: 8084

spring:
  application:
    name: The ShareGame Gateway

gateway:
  host: 192.168.0.180

#  cloud:
#    gateway:
#      routes:
#        - id: portfolio_route
#          uri: http://localhost:8083/portfolio/
#          predicates:
#            - Path=/portfolio/**